[package]
name = "minitel"
version = "0.3.2"
edition = "2024"
authors = ["Pierre Lulé <pierre@lule.fr>"]
description = "Minitel interaction library"
readme = "README.md"
repository = "https://github.com/plule/minitel"
license = "MIT OR Apache-2.0"
categories = ["hardware-support", "api-bindings", "embedded", "web-programming"]
keywords = ["minitel", "videotex", "teletel"]
exclude = [".gitignore", "*.code-workspace", ".github", ".embuild", ".vscode"]

[workspace]
members = ["minitel-app-example"]


[dependencies]
ratatui = { version = "0.30", optional = true, default-features = false, features = [] }
axum = { version = "0.8", optional = true, default-features = false, features = ["ws"] }
esp-idf-hal = { version = "0.46", optional = true }
num_enum = "0.7"
smallvec = "1.15"
unicode-normalization = "0.1"
log = "0.4"
futures = { version = "0.3", optional = true }
#thiserror = "2"

[features]
default = []
esp = ["dep:esp-idf-hal"]
espdoc = []
ratatui = ["dep:ratatui"]
docsrs = ["ratatui", "axum", "espdoc", "futures"]
axum = ["dep:axum"]
futures = ["dep:futures"]
invalidation-group = ["ratatui/underline-color"]

[dev-dependencies]
env_logger = "0.11"
tungstenite = "0.30"
ratatui = { version = "0.30", default-features = false }
tokio = { version = "1.53", features = ["full"] }
futures = "0.3"

[package.metadata.docs.rs]
no-default-features = true
features = ["docsrs"]
