[package]
name = "minitel-app-example"
version = "0.1.1"
edition = "2024"
authors = ["Pierre Lulé <pierre@lule.fr>"]
description = "Example application running on a minitel"
readme = "../README.md"
repository = "https://github.com/plule/minitel"
license = "MIT OR Apache-2.0"
categories = ["hardware-support", "api-bindings", "embedded", "web-programming"]
keywords = ["minitel", "videotex", "teletel"]
exclude = ["*.code-workspace", ".github", ".embuild", ".vscode"]

[dependencies]
env_logger = "0.11"
log = "0.4"
ratatui = { version = "0.30", default-features = false, features = [
    "widget-calendar",
] }
strum = { version = "0.28", features = ["derive"] }
time = "0.3"
tungstenite = { version = "0.30", optional = true }
minitel = { path = "..", features = ["ratatui"] }
esp-idf-svc = { version = "0.52", features = [
    "critical-section",
    "embassy-time-driver",
    "embassy-sync",
], optional = true}
embassy-time-queue-utils = { version = "0.3", optional = true, features = ["generic-queue-8"] }
tui-big-text = "0.8"
axum = { version = "0.8", features = ["ws"], optional = true}
open = { version = "5.4", optional = true }
tokio = { version = "1.53", features = ["rt", "net", "io-util", "macros"]}
tower-http = { version = "0.7", features = ["trace", "fs"], optional = true}
tracing-subscriber = { version = "0.3", features = ["env-filter"],  optional = true}
tracing = "0.1"
tokio-util = { version = "0.7", optional = true, features = ["compat"]}
futures = { version = "0.3", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true}
serde_json = { version = "1.0", optional = true }
base64 = { version = "0.23", optional = true }
clap = { version = "4.6", optional = true, features = ["derive"] }

[features]
default = ["esp"]
esp = ["minitel/esp", "dep:esp-idf-svc", "dep:embassy-time-queue-utils"]
axum = ["minitel/axum", "tokio/rt-multi-thread", "dep:axum", "dep:tower-http", "dep:tracing-subscriber", "dep:serde", "dep:serde_json", "dep:base64", "dep:clap", "dep:open"]
tcp = ["minitel/futures", "tokio/rt-multi-thread", "dep:tokio-util", "dep:futures", "dep:tracing-subscriber"]

[build-dependencies]
embuild = { version = "0.33", features = ["espidf"] }
cc = "=1.1.30" # Version "1.1.30" necessary until a new version of `esp-idf-sys` is released
